package com.mahi.aitaskmanager.controller;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.mahi.aitaskmanager.dto.SubtaskRequest;
import com.mahi.aitaskmanager.dto.SubtaskResponse;
import com.mahi.aitaskmanager.dto.TaskResponse;
import com.mahi.aitaskmanager.enums.SubtaskStatus;
import com.mahi.aitaskmanager.service.AiService;
import com.mahi.aitaskmanager.service.SubtaskService;
import com.mahi.aitaskmanager.service.TaskService;
import java.time.LocalDateTime;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(AiController.class)
public class AiControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private TaskService taskService;

    @MockBean
    private AiService aiService;

    @MockBean
    private SubtaskService subtaskService;

    @Test
    void breakdownReturnsSuggestions() throws Exception {
        TaskResponse task = new TaskResponse();
        task.setId(1L);
        task.setTitle("New feature");
        task.setDescription("Do stuff");

        when(taskService.getTaskById(1L)).thenReturn(task);
        when(aiService.suggestSubtasks(task.getTitle(), task.getDescription()))
                .thenReturn(List.of("step1", "step2"));

        mockMvc.perform(post("/api/tasks/1/ai/breakdown").contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().json("[\"step1\",\"step2\"]"));
    }

    @Test
    void breakdownPersistsSuggestionsWhenRequested() throws Exception {
        TaskResponse task = new TaskResponse();
        task.setId(1L);
        task.setTitle("New feature");
        task.setDescription("Do stuff");

        when(taskService.getTaskById(1L)).thenReturn(task);
        when(aiService.suggestSubtasks(task.getTitle(), task.getDescription()))
                .thenReturn(List.of("step1", "step2"));

        SubtaskResponse first = new SubtaskResponse();
        first.setId(50L);
        first.setTaskId(1L);
        first.setTitle("step1");
        first.setDescription("Generated by AI");
        first.setStatus(SubtaskStatus.TODO);
        first.setOrd(0);
        first.setCreatedAt(LocalDateTime.now());
        first.setUpdatedAt(LocalDateTime.now());

        SubtaskResponse second = new SubtaskResponse();
        second.setId(51L);
        second.setTaskId(1L);
        second.setTitle("step2");
        second.setDescription("Generated by AI");
        second.setStatus(SubtaskStatus.TODO);
        second.setOrd(1);
        second.setCreatedAt(LocalDateTime.now());
        second.setUpdatedAt(LocalDateTime.now());

        when(subtaskService.createSubtask(eq(1L), any(SubtaskRequest.class)))
                .thenReturn(first, second);

        mockMvc.perform(post("/api/tasks/1/ai/breakdown?persist=true").contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().json("[{\"id\":50,\"taskId\":1,\"title\":\"step1\"},{\"id\":51,\"taskId\":1,\"title\":\"step2\"}]"));
    }
}
