package com.mahi.aitaskmanager.controller;

import com.mahi.aitaskmanager.dto.SubtaskRequest;
import com.mahi.aitaskmanager.dto.SubtaskResponse;
import com.mahi.aitaskmanager.dto.TaskResponse;
import com.mahi.aitaskmanager.enums.SubtaskStatus;
import com.mahi.aitaskmanager.service.AiService;
import com.mahi.aitaskmanager.service.SubtaskService;
import com.mahi.aitaskmanager.service.TaskService;
import java.util.ArrayList;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/tasks/{id}/ai")
public class AiController {

    private final TaskService taskService;
    private final AiService aiService;
    private final SubtaskService subtaskService;

    public AiController(TaskService taskService, AiService aiService, SubtaskService subtaskService) {
        this.taskService = taskService;
        this.aiService = aiService;
        this.subtaskService = subtaskService;
    }

    @PostMapping("/breakdown")
    public ResponseEntity<?> breakdownTask(@PathVariable Long id,
                                          @RequestParam(defaultValue = "false") boolean persist) {
        TaskResponse task = taskService.getTaskById(id);
        if (task == null) {
            return ResponseEntity.notFound().build();
        }

        List<String> suggestions = aiService.suggestSubtasks(task.getTitle(), task.getDescription());
        if (persist) {
            List<SubtaskResponse> created = new ArrayList<>();
            for (int i = 0; i < suggestions.size(); i++) {
                SubtaskRequest request = new SubtaskRequest();
                request.setTitle(suggestions.get(i));
                request.setDescription("Generated by AI");
                request.setStatus(SubtaskStatus.TODO);
                request.setOrd(i);
                created.add(subtaskService.createSubtask(id, request));
            }
            return ResponseEntity.ok(created);
        }

        return ResponseEntity.ok(suggestions);
    }
}
